// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJNpL2xOAsRY7bjSyGpJ1SWlpchrCd384',
    appId: '1:1003587810960:web:e045e296ea07bfc5d88a15',
    messagingSenderId: '1003587810960',
    projectId: 'quizapp-1fc58',
    authDomain: 'quizapp-1fc58.firebaseapp.com',
    storageBucket: 'quizapp-1fc58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCANT8h3yVnH4j6QRT4y_JEcQKAXw1mrY4',
    appId: '1:1003587810960:android:a42348d5cfccc5e1d88a15',
    messagingSenderId: '1003587810960',
    projectId: 'quizapp-1fc58',
    storageBucket: 'quizapp-1fc58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYaCXssjpob7o9N1RDVnV4_JQfWcLfCzg',
    appId: '1:1003587810960:ios:3bead37ea97dea90d88a15',
    messagingSenderId: '1003587810960',
    projectId: 'quizapp-1fc58',
    storageBucket: 'quizapp-1fc58.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYaCXssjpob7o9N1RDVnV4_JQfWcLfCzg',
    appId: '1:1003587810960:ios:3bead37ea97dea90d88a15',
    messagingSenderId: '1003587810960',
    projectId: 'quizapp-1fc58',
    storageBucket: 'quizapp-1fc58.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJNpL2xOAsRY7bjSyGpJ1SWlpchrCd384',
    appId: '1:1003587810960:web:52f85629f0821955d88a15',
    messagingSenderId: '1003587810960',
    projectId: 'quizapp-1fc58',
    authDomain: 'quizapp-1fc58.firebaseapp.com',
    storageBucket: 'quizapp-1fc58.firebasestorage.app',
  );
}
